name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to Modrinth
        uses: Kira-NT/mc-publish@v3
        with:
          files: dist/*.jar

          modrinth-id: IqCPvv9e
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # curseforge-id: 394468
          # curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
